[project]
name = "optimal-flexibility"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pydantic>=2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/assets", "src/optimizer"]

[tool.pyright]
extraPaths = ["src"]
venvPath = "."
venv = ".venv"
